version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/code/app
      - exclude:/code/app/node_modules
    networks:
      - web
    command: yarn start

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/code/app
    networks:
      - web
    command: uvicorn app.main:app --host 0.0.0.0 --port 3001

  proxy:
    container_name: proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile
    restart: always
    networks:
      - web
    depends_on:
      - backend
      - frontend
    ports:
      - "8000:8000"

networks:
  web:

volumes:
  exclude:
